// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDuplicates(arg1) {
  return window['go']['main']['App']['CheckDuplicates'](arg1);
}

export function CreateBook(arg1) {
  return window['go']['main']['App']['CreateBook'](arg1);
}

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function GenerateBookID() {
  return window['go']['main']['App']['GenerateBookID']();
}

export function GenerateCSVExport(arg1) {
  return window['go']['main']['App']['GenerateCSVExport'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListActiveBooks() {
  return window['go']['main']['App']['ListActiveBooks']();
}

export function ListAllBooks() {
  return window['go']['main']['App']['ListAllBooks']();
}

export function ListCompletedBooks() {
  return window['go']['main']['App']['ListCompletedBooks']();
}

export function MarkBookComplete(arg1) {
  return window['go']['main']['App']['MarkBookComplete'](arg1);
}

export function NowTimestamp() {
  return window['go']['main']['App']['NowTimestamp']();
}

export function OpenCSVFile() {
  return window['go']['main']['App']['OpenCSVFile']();
}

export function ParseCSVBooks(arg1) {
  return window['go']['main']['App']['ParseCSVBooks'](arg1);
}

export function SaveCSVFile(arg1, arg2) {
  return window['go']['main']['App']['SaveCSVFile'](arg1, arg2);
}

export function UpdateBook(arg1) {
  return window['go']['main']['App']['UpdateBook'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ValidateCreateBookRequest(arg1) {
  return window['go']['main']['App']['ValidateCreateBookRequest'](arg1);
}

export function ValidateProgressUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateProgressUpdate'](arg1, arg2, arg3);
}

export function ValidateSettings(arg1) {
  return window['go']['main']['App']['ValidateSettings'](arg1);
}
