// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CheckDuplicates(arg1:Array<model.CSVBookRecord>):Promise<Array<model.DuplicateReport>>;

export function CreateBook(arg1:model.CreateBookRequest):Promise<model.Book>;

export function DeleteBook(arg1:string):Promise<void>;

export function GenerateBookID():Promise<string>;

export function GenerateCSVExport(arg1:Array<model.Book>):Promise<string>;

export function GetSettings():Promise<model.UserSettings>;

export function ListActiveBooks():Promise<Array<model.Book>>;

export function ListAllBooks():Promise<Array<model.Book>>;

export function ListCompletedBooks():Promise<Array<model.Book>>;

export function MarkBookComplete(arg1:string):Promise<model.Book>;

export function NowTimestamp():Promise<string>;

export function OpenCSVFile():Promise<string>;

export function ParseCSVBooks(arg1:string):Promise<Array<model.CSVBookRecord>>;

export function SaveCSVFile(arg1:string,arg2:string):Promise<boolean>;

export function UpdateBook(arg1:model.UpdateBookRequest):Promise<model.Book>;

export function UpdateSettings(arg1:model.UpdateSettingsRequest):Promise<model.UserSettings>;

export function ValidateCreateBookRequest(arg1:model.CreateBookRequest):Promise<string>;

export function ValidateProgressUpdate(arg1:number,arg2:number,arg3:string):Promise<string>;

export function ValidateSettings(arg1:model.UpdateSettingsRequest):Promise<string>;
